branch: release
npmPublish: false
verifyConditions: 
  - '@semantic-release/changelog'
  - '@semantic-release/git'
prepare:
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  -
    path: '@semantic-release/exec'
    cmd: "./update-version-dist.sh ${nextRelease.version}"
  - '@semantic-release/git'
